// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReturnCode int32

const (
	ReturnCode_OK                    ReturnCode = 0
	ReturnCode_INTERNAL_ERROR        ReturnCode = 1
	ReturnCode_REQUEST_PARAM_ILLEGAL ReturnCode = 2
	ReturnCode_OTHER_ERROR           ReturnCode = 99
)

var ReturnCode_name = map[int32]string{
	0:  "OK",
	1:  "INTERNAL_ERROR",
	2:  "REQUEST_PARAM_ILLEGAL",
	99: "OTHER_ERROR",
}

var ReturnCode_value = map[string]int32{
	"OK":                    0,
	"INTERNAL_ERROR":        1,
	"REQUEST_PARAM_ILLEGAL": 2,
	"OTHER_ERROR":           99,
}

func (x ReturnCode) String() string {
	return proto.EnumName(ReturnCode_name, int32(x))
}

func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type AutopayRequest_AutopayCode int32

const (
	AutopayRequest_YES AutopayRequest_AutopayCode = 0
	AutopayRequest_NO  AutopayRequest_AutopayCode = 1
)

var AutopayRequest_AutopayCode_name = map[int32]string{
	0: "YES",
	1: "NO",
}

var AutopayRequest_AutopayCode_value = map[string]int32{
	"YES": 0,
	"NO":  1,
}

func (x AutopayRequest_AutopayCode) String() string {
	return proto.EnumName(AutopayRequest_AutopayCode_name, int32(x))
}

func (AutopayRequest_AutopayCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9, 0}
}

type RegisterRequest struct {
	UserAddress          string   `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

type RegisterResponse struct {
	Code                 ReturnCode `protobuf:"varint,1,opt,name=code,proto3,enum=soter_user.ReturnCode" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetCode() ReturnCode {
	if m != nil {
		return m.Code
	}
	return ReturnCode_OK
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HistoryRequest struct {
	UserAddress          string   `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	StartUnixtime        int64    `protobuf:"varint,2,opt,name=start_unixtime,json=startUnixtime,proto3" json:"start_unixtime,omitempty"`
	EndUnixtime          int64    `protobuf:"varint,3,opt,name=end_unixtime,json=endUnixtime,proto3" json:"end_unixtime,omitempty"`
	Offset               int32    `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryRequest) Reset()         { *m = HistoryRequest{} }
func (m *HistoryRequest) String() string { return proto.CompactTextString(m) }
func (*HistoryRequest) ProtoMessage()    {}
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *HistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryRequest.Unmarshal(m, b)
}
func (m *HistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryRequest.Marshal(b, m, deterministic)
}
func (m *HistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryRequest.Merge(m, src)
}
func (m *HistoryRequest) XXX_Size() int {
	return xxx_messageInfo_HistoryRequest.Size(m)
}
func (m *HistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryRequest proto.InternalMessageInfo

func (m *HistoryRequest) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *HistoryRequest) GetStartUnixtime() int64 {
	if m != nil {
		return m.StartUnixtime
	}
	return 0
}

func (m *HistoryRequest) GetEndUnixtime() int64 {
	if m != nil {
		return m.EndUnixtime
	}
	return 0
}

func (m *HistoryRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *HistoryRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type UploadHistoryRequest struct {
	Request              *HistoryRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UploadHistoryRequest) Reset()         { *m = UploadHistoryRequest{} }
func (m *UploadHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*UploadHistoryRequest) ProtoMessage()    {}
func (*UploadHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UploadHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadHistoryRequest.Unmarshal(m, b)
}
func (m *UploadHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadHistoryRequest.Marshal(b, m, deterministic)
}
func (m *UploadHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadHistoryRequest.Merge(m, src)
}
func (m *UploadHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_UploadHistoryRequest.Size(m)
}
func (m *UploadHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadHistoryRequest proto.InternalMessageInfo

func (m *UploadHistoryRequest) GetRequest() *HistoryRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type UploadHistoryResponse struct {
	Code                 ReturnCode                            `protobuf:"varint,1,opt,name=code,proto3,enum=soter_user.ReturnCode" json:"code,omitempty"`
	Message              string                                `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UploadRecordArray    []*UploadHistoryResponse_UploadRecord `protobuf:"bytes,3,rep,name=UploadRecordArray,proto3" json:"UploadRecordArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *UploadHistoryResponse) Reset()         { *m = UploadHistoryResponse{} }
func (m *UploadHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*UploadHistoryResponse) ProtoMessage()    {}
func (*UploadHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UploadHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadHistoryResponse.Unmarshal(m, b)
}
func (m *UploadHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadHistoryResponse.Marshal(b, m, deterministic)
}
func (m *UploadHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadHistoryResponse.Merge(m, src)
}
func (m *UploadHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_UploadHistoryResponse.Size(m)
}
func (m *UploadHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadHistoryResponse proto.InternalMessageInfo

func (m *UploadHistoryResponse) GetCode() ReturnCode {
	if m != nil {
		return m.Code
	}
	return ReturnCode_OK
}

func (m *UploadHistoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UploadHistoryResponse) GetUploadRecordArray() []*UploadHistoryResponse_UploadRecord {
	if m != nil {
		return m.UploadRecordArray
	}
	return nil
}

type UploadHistoryResponse_UploadRecord struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize             int64    `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	UploadTime           string   `protobuf:"bytes,5,opt,name=upload_time,json=uploadTime,proto3" json:"upload_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadHistoryResponse_UploadRecord) Reset()         { *m = UploadHistoryResponse_UploadRecord{} }
func (m *UploadHistoryResponse_UploadRecord) String() string { return proto.CompactTextString(m) }
func (*UploadHistoryResponse_UploadRecord) ProtoMessage()    {}
func (*UploadHistoryResponse_UploadRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4, 0}
}

func (m *UploadHistoryResponse_UploadRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadHistoryResponse_UploadRecord.Unmarshal(m, b)
}
func (m *UploadHistoryResponse_UploadRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadHistoryResponse_UploadRecord.Marshal(b, m, deterministic)
}
func (m *UploadHistoryResponse_UploadRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadHistoryResponse_UploadRecord.Merge(m, src)
}
func (m *UploadHistoryResponse_UploadRecord) XXX_Size() int {
	return xxx_messageInfo_UploadHistoryResponse_UploadRecord.Size(m)
}
func (m *UploadHistoryResponse_UploadRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadHistoryResponse_UploadRecord.DiscardUnknown(m)
}

var xxx_messageInfo_UploadHistoryResponse_UploadRecord proto.InternalMessageInfo

func (m *UploadHistoryResponse_UploadRecord) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *UploadHistoryResponse_UploadRecord) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *UploadHistoryResponse_UploadRecord) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *UploadHistoryResponse_UploadRecord) GetUploadTime() string {
	if m != nil {
		return m.UploadTime
	}
	return ""
}

type DepositHistoryRequest struct {
	Request              *HistoryRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DepositHistoryRequest) Reset()         { *m = DepositHistoryRequest{} }
func (m *DepositHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*DepositHistoryRequest) ProtoMessage()    {}
func (*DepositHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *DepositHistoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositHistoryRequest.Unmarshal(m, b)
}
func (m *DepositHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositHistoryRequest.Marshal(b, m, deterministic)
}
func (m *DepositHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositHistoryRequest.Merge(m, src)
}
func (m *DepositHistoryRequest) XXX_Size() int {
	return xxx_messageInfo_DepositHistoryRequest.Size(m)
}
func (m *DepositHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositHistoryRequest proto.InternalMessageInfo

func (m *DepositHistoryRequest) GetRequest() *HistoryRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type DepositHistoryResponse struct {
	Code                 ReturnCode                              `protobuf:"varint,1,opt,name=code,proto3,enum=soter_user.ReturnCode" json:"code,omitempty"`
	Message              string                                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DepositRecordArray   []*DepositHistoryResponse_DepositRecord `protobuf:"bytes,3,rep,name=DepositRecordArray,proto3" json:"DepositRecordArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *DepositHistoryResponse) Reset()         { *m = DepositHistoryResponse{} }
func (m *DepositHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*DepositHistoryResponse) ProtoMessage()    {}
func (*DepositHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *DepositHistoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositHistoryResponse.Unmarshal(m, b)
}
func (m *DepositHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositHistoryResponse.Marshal(b, m, deterministic)
}
func (m *DepositHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositHistoryResponse.Merge(m, src)
}
func (m *DepositHistoryResponse) XXX_Size() int {
	return xxx_messageInfo_DepositHistoryResponse.Size(m)
}
func (m *DepositHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepositHistoryResponse proto.InternalMessageInfo

func (m *DepositHistoryResponse) GetCode() ReturnCode {
	if m != nil {
		return m.Code
	}
	return ReturnCode_OK
}

func (m *DepositHistoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DepositHistoryResponse) GetDepositRecordArray() []*DepositHistoryResponse_DepositRecord {
	if m != nil {
		return m.DepositRecordArray
	}
	return nil
}

type DepositHistoryResponse_DepositRecord struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Balance              int64    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	BlockTimestamp       string   `protobuf:"bytes,3,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositHistoryResponse_DepositRecord) Reset()         { *m = DepositHistoryResponse_DepositRecord{} }
func (m *DepositHistoryResponse_DepositRecord) String() string { return proto.CompactTextString(m) }
func (*DepositHistoryResponse_DepositRecord) ProtoMessage()    {}
func (*DepositHistoryResponse_DepositRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6, 0}
}

func (m *DepositHistoryResponse_DepositRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositHistoryResponse_DepositRecord.Unmarshal(m, b)
}
func (m *DepositHistoryResponse_DepositRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositHistoryResponse_DepositRecord.Marshal(b, m, deterministic)
}
func (m *DepositHistoryResponse_DepositRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositHistoryResponse_DepositRecord.Merge(m, src)
}
func (m *DepositHistoryResponse_DepositRecord) XXX_Size() int {
	return xxx_messageInfo_DepositHistoryResponse_DepositRecord.Size(m)
}
func (m *DepositHistoryResponse_DepositRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositHistoryResponse_DepositRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DepositHistoryResponse_DepositRecord proto.InternalMessageInfo

func (m *DepositHistoryResponse_DepositRecord) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *DepositHistoryResponse_DepositRecord) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *DepositHistoryResponse_DepositRecord) GetBlockTimestamp() string {
	if m != nil {
		return m.BlockTimestamp
	}
	return ""
}

type OrderListRequest struct {
	Request              *HistoryRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OrderListRequest) Reset()         { *m = OrderListRequest{} }
func (m *OrderListRequest) String() string { return proto.CompactTextString(m) }
func (*OrderListRequest) ProtoMessage()    {}
func (*OrderListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *OrderListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderListRequest.Unmarshal(m, b)
}
func (m *OrderListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderListRequest.Marshal(b, m, deterministic)
}
func (m *OrderListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderListRequest.Merge(m, src)
}
func (m *OrderListRequest) XXX_Size() int {
	return xxx_messageInfo_OrderListRequest.Size(m)
}
func (m *OrderListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderListRequest proto.InternalMessageInfo

func (m *OrderListRequest) GetRequest() *HistoryRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type OrderListResponse struct {
	Code                 ReturnCode                       `protobuf:"varint,1,opt,name=code,proto3,enum=soter_user.ReturnCode" json:"code,omitempty"`
	Message              string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	OrderRecordArray     []*OrderListResponse_OrderRecord `protobuf:"bytes,3,rep,name=OrderRecordArray,proto3" json:"OrderRecordArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *OrderListResponse) Reset()         { *m = OrderListResponse{} }
func (m *OrderListResponse) String() string { return proto.CompactTextString(m) }
func (*OrderListResponse) ProtoMessage()    {}
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *OrderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderListResponse.Unmarshal(m, b)
}
func (m *OrderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderListResponse.Marshal(b, m, deterministic)
}
func (m *OrderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderListResponse.Merge(m, src)
}
func (m *OrderListResponse) XXX_Size() int {
	return xxx_messageInfo_OrderListResponse.Size(m)
}
func (m *OrderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderListResponse proto.InternalMessageInfo

func (m *OrderListResponse) GetCode() ReturnCode {
	if m != nil {
		return m.Code
	}
	return ReturnCode_OK
}

func (m *OrderListResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderListResponse) GetOrderRecordArray() []*OrderListResponse_OrderRecord {
	if m != nil {
		return m.OrderRecordArray
	}
	return nil
}

type OrderListResponse_OrderRecord struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Fee                  int64    `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	SaveTime             int64    `protobuf:"varint,3,opt,name=save_time,json=saveTime,proto3" json:"save_time,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	FileHash             string   `protobuf:"bytes,6,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileName             string   `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize             int64    `protobuf:"varint,8,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderListResponse_OrderRecord) Reset()         { *m = OrderListResponse_OrderRecord{} }
func (m *OrderListResponse_OrderRecord) String() string { return proto.CompactTextString(m) }
func (*OrderListResponse_OrderRecord) ProtoMessage()    {}
func (*OrderListResponse_OrderRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8, 0}
}

func (m *OrderListResponse_OrderRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderListResponse_OrderRecord.Unmarshal(m, b)
}
func (m *OrderListResponse_OrderRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderListResponse_OrderRecord.Marshal(b, m, deterministic)
}
func (m *OrderListResponse_OrderRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderListResponse_OrderRecord.Merge(m, src)
}
func (m *OrderListResponse_OrderRecord) XXX_Size() int {
	return xxx_messageInfo_OrderListResponse_OrderRecord.Size(m)
}
func (m *OrderListResponse_OrderRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderListResponse_OrderRecord.DiscardUnknown(m)
}

var xxx_messageInfo_OrderListResponse_OrderRecord proto.InternalMessageInfo

func (m *OrderListResponse_OrderRecord) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *OrderListResponse_OrderRecord) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *OrderListResponse_OrderRecord) GetSaveTime() int64 {
	if m != nil {
		return m.SaveTime
	}
	return 0
}

func (m *OrderListResponse_OrderRecord) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *OrderListResponse_OrderRecord) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderListResponse_OrderRecord) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *OrderListResponse_OrderRecord) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *OrderListResponse_OrderRecord) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type AutopayRequest struct {
	UserAddress          string                     `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	Code                 AutopayRequest_AutopayCode `protobuf:"varint,2,opt,name=code,proto3,enum=soter_user.AutopayRequest_AutopayCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AutopayRequest) Reset()         { *m = AutopayRequest{} }
func (m *AutopayRequest) String() string { return proto.CompactTextString(m) }
func (*AutopayRequest) ProtoMessage()    {}
func (*AutopayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *AutopayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutopayRequest.Unmarshal(m, b)
}
func (m *AutopayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutopayRequest.Marshal(b, m, deterministic)
}
func (m *AutopayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutopayRequest.Merge(m, src)
}
func (m *AutopayRequest) XXX_Size() int {
	return xxx_messageInfo_AutopayRequest.Size(m)
}
func (m *AutopayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AutopayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AutopayRequest proto.InternalMessageInfo

func (m *AutopayRequest) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *AutopayRequest) GetCode() AutopayRequest_AutopayCode {
	if m != nil {
		return m.Code
	}
	return AutopayRequest_YES
}

type AutopayResponse struct {
	Code                 ReturnCode `protobuf:"varint,1,opt,name=code,proto3,enum=soter_user.ReturnCode" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AutopayResponse) Reset()         { *m = AutopayResponse{} }
func (m *AutopayResponse) String() string { return proto.CompactTextString(m) }
func (*AutopayResponse) ProtoMessage()    {}
func (*AutopayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *AutopayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutopayResponse.Unmarshal(m, b)
}
func (m *AutopayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutopayResponse.Marshal(b, m, deterministic)
}
func (m *AutopayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutopayResponse.Merge(m, src)
}
func (m *AutopayResponse) XXX_Size() int {
	return xxx_messageInfo_AutopayResponse.Size(m)
}
func (m *AutopayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AutopayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AutopayResponse proto.InternalMessageInfo

func (m *AutopayResponse) GetCode() ReturnCode {
	if m != nil {
		return m.Code
	}
	return ReturnCode_OK
}

func (m *AutopayResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateInfoRequest struct {
	UserAddress          string   `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfoRequest) Reset()         { *m = UpdateInfoRequest{} }
func (m *UpdateInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInfoRequest) ProtoMessage()    {}
func (*UpdateInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *UpdateInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfoRequest.Unmarshal(m, b)
}
func (m *UpdateInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfoRequest.Merge(m, src)
}
func (m *UpdateInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInfoRequest.Size(m)
}
func (m *UpdateInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfoRequest proto.InternalMessageInfo

func (m *UpdateInfoRequest) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

func (m *UpdateInfoRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateInfoRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type UpdateInfoResponse struct {
	Code                 ReturnCode `protobuf:"varint,1,opt,name=code,proto3,enum=soter_user.ReturnCode" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateInfoResponse) Reset()         { *m = UpdateInfoResponse{} }
func (m *UpdateInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateInfoResponse) ProtoMessage()    {}
func (*UpdateInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *UpdateInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfoResponse.Unmarshal(m, b)
}
func (m *UpdateInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfoResponse.Marshal(b, m, deterministic)
}
func (m *UpdateInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfoResponse.Merge(m, src)
}
func (m *UpdateInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateInfoResponse.Size(m)
}
func (m *UpdateInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfoResponse proto.InternalMessageInfo

func (m *UpdateInfoResponse) GetCode() ReturnCode {
	if m != nil {
		return m.Code
	}
	return ReturnCode_OK
}

func (m *UpdateInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("soter_user.ReturnCode", ReturnCode_name, ReturnCode_value)
	proto.RegisterEnum("soter_user.AutopayRequest_AutopayCode", AutopayRequest_AutopayCode_name, AutopayRequest_AutopayCode_value)
	proto.RegisterType((*RegisterRequest)(nil), "soter_user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "soter_user.RegisterResponse")
	proto.RegisterType((*HistoryRequest)(nil), "soter_user.HistoryRequest")
	proto.RegisterType((*UploadHistoryRequest)(nil), "soter_user.UploadHistoryRequest")
	proto.RegisterType((*UploadHistoryResponse)(nil), "soter_user.UploadHistoryResponse")
	proto.RegisterType((*UploadHistoryResponse_UploadRecord)(nil), "soter_user.UploadHistoryResponse.UploadRecord")
	proto.RegisterType((*DepositHistoryRequest)(nil), "soter_user.DepositHistoryRequest")
	proto.RegisterType((*DepositHistoryResponse)(nil), "soter_user.DepositHistoryResponse")
	proto.RegisterType((*DepositHistoryResponse_DepositRecord)(nil), "soter_user.DepositHistoryResponse.DepositRecord")
	proto.RegisterType((*OrderListRequest)(nil), "soter_user.OrderListRequest")
	proto.RegisterType((*OrderListResponse)(nil), "soter_user.OrderListResponse")
	proto.RegisterType((*OrderListResponse_OrderRecord)(nil), "soter_user.OrderListResponse.OrderRecord")
	proto.RegisterType((*AutopayRequest)(nil), "soter_user.AutopayRequest")
	proto.RegisterType((*AutopayResponse)(nil), "soter_user.AutopayResponse")
	proto.RegisterType((*UpdateInfoRequest)(nil), "soter_user.UpdateInfoRequest")
	proto.RegisterType((*UpdateInfoResponse)(nil), "soter_user.UpdateInfoResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 898 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xf6, 0x6f, 0x7e, 0xce, 0xb6, 0x8e, 0x3b, 0x24, 0x91, 0x71, 0x9a, 0x92, 0xac, 0x04, 0x84,
	0x5e, 0x58, 0x28, 0xf4, 0x8a, 0x3b, 0x0b, 0xac, 0xc4, 0xaa, 0x6b, 0xd3, 0xb1, 0x2d, 0x0a, 0x02,
	0x6d, 0x27, 0xde, 0xe3, 0x64, 0x85, 0x77, 0xc7, 0xcc, 0x8c, 0xab, 0xb4, 0x3c, 0x04, 0xe2, 0x05,
	0xb8, 0x47, 0xbc, 0x00, 0xef, 0xc4, 0x4b, 0xa0, 0x99, 0x9d, 0xb5, 0x77, 0x63, 0x27, 0x25, 0xaa,
	0xef, 0xe6, 0x7c, 0xe7, 0xcc, 0x37, 0x67, 0xce, 0xdf, 0x0c, 0xc0, 0x4c, 0xa2, 0x68, 0x4c, 0x05,
	0x57, 0x9c, 0x80, 0xe4, 0x0a, 0x85, 0xa7, 0x11, 0xf7, 0x19, 0xec, 0x50, 0xbc, 0x0c, 0xa4, 0x42,
	0x41, 0xf1, 0xd7, 0x19, 0x4a, 0x45, 0x8e, 0xe1, 0x81, 0x56, 0x79, 0xcc, 0xf7, 0x05, 0x4a, 0x59,
	0xcb, 0x1f, 0xe5, 0x4f, 0xb6, 0xa9, 0xa3, 0xb1, 0x66, 0x0c, 0xb9, 0xaf, 0xa0, 0xba, 0xd8, 0x25,
	0xa7, 0x3c, 0x92, 0x48, 0x9e, 0x42, 0x69, 0xc4, 0x7d, 0x34, 0xe6, 0x95, 0xd3, 0xfd, 0xc6, 0xe2,
	0x90, 0x06, 0x45, 0x35, 0x13, 0xd1, 0x37, 0xdc, 0x47, 0x6a, 0x6c, 0x48, 0x0d, 0x36, 0x43, 0x94,
	0x92, 0x5d, 0x62, 0xad, 0x60, 0xd8, 0x13, 0xd1, 0xfd, 0x3b, 0x0f, 0x95, 0xf3, 0x40, 0x2a, 0x2e,
	0xde, 0xfe, 0x7f, 0x7f, 0xc8, 0xa7, 0x50, 0x91, 0x8a, 0x09, 0xe5, 0xcd, 0xa2, 0xe0, 0x5a, 0x05,
	0x61, 0x4c, 0x5b, 0xa4, 0x0f, 0x0d, 0x3a, 0xb4, 0xa0, 0x66, 0xc2, 0xc8, 0x5f, 0x18, 0x15, 0x8d,
	0x91, 0x83, 0x91, 0x3f, 0x37, 0xd9, 0x87, 0x0d, 0x3e, 0x1e, 0x4b, 0x54, 0xb5, 0xd2, 0x51, 0xfe,
	0xa4, 0x4c, 0xad, 0x44, 0x76, 0xa1, 0x3c, 0x09, 0xc2, 0x40, 0xd5, 0xca, 0x06, 0x8e, 0x05, 0xb7,
	0x03, 0xbb, 0xc3, 0xe9, 0x84, 0x33, 0xff, 0x86, 0xcb, 0xcf, 0x60, 0x53, 0xc4, 0x4b, 0xe3, 0xad,
	0x73, 0x5a, 0x4f, 0x87, 0x23, 0x6b, 0x4c, 0x13, 0x53, 0xf7, 0x9f, 0x02, 0xec, 0xdd, 0xa0, 0x5b,
	0x67, 0x6c, 0xc9, 0x4f, 0xf0, 0x28, 0xa6, 0xa7, 0x38, 0xe2, 0xc2, 0x6f, 0x0a, 0xc1, 0xde, 0xd6,
	0x8a, 0x47, 0xc5, 0x13, 0xe7, 0xb4, 0x91, 0xa6, 0x5c, 0xe9, 0x43, 0x23, 0xbd, 0x95, 0x2e, 0x13,
	0xd5, 0x7f, 0x83, 0x07, 0x69, 0x90, 0x54, 0xa1, 0x38, 0x0a, 0x7c, 0x9b, 0x2d, 0xbd, 0x24, 0x07,
	0xb0, 0x3d, 0x0e, 0x26, 0xe8, 0x45, 0x2c, 0x4c, 0x7c, 0xdb, 0xd2, 0x40, 0x97, 0x85, 0x38, 0x57,
	0xca, 0xe0, 0x5d, 0x92, 0x18, 0xa3, 0xec, 0x07, 0xef, 0x90, 0x7c, 0x02, 0xce, 0xcc, 0x70, 0x7b,
	0x26, 0x6f, 0x65, 0xb3, 0x17, 0x62, 0x68, 0x10, 0x84, 0xe8, 0xbe, 0x80, 0xbd, 0x6f, 0x71, 0xca,
	0x65, 0xa0, 0xd6, 0x92, 0x89, 0xbf, 0x0a, 0xb0, 0x7f, 0x93, 0x6f, 0xad, 0xa9, 0x78, 0x0d, 0xc4,
	0xf2, 0x2f, 0xe7, 0xe2, 0xcb, 0x34, 0xe7, 0x6a, 0x2f, 0x1a, 0x99, 0xcd, 0x74, 0x05, 0x57, 0xfd,
	0x12, 0x1e, 0x66, 0x50, 0xf2, 0x11, 0x94, 0xd5, 0xb5, 0x37, 0xcf, 0x48, 0x49, 0x5d, 0xb7, 0x7d,
	0xed, 0xe1, 0x05, 0x9b, 0xb0, 0x68, 0x94, 0x74, 0x4c, 0x22, 0x92, 0xcf, 0x61, 0xe7, 0x62, 0xc2,
	0x47, 0xbf, 0x98, 0x88, 0x4b, 0xc5, 0xc2, 0xa9, 0xc9, 0xca, 0x36, 0xad, 0x18, 0x78, 0x90, 0xa0,
	0xee, 0x39, 0x54, 0x7b, 0xc2, 0x47, 0xd1, 0x09, 0xa4, 0xfa, 0xb0, 0xa8, 0xff, 0x59, 0x84, 0x47,
	0x29, 0xaa, 0xb5, 0x06, 0x7c, 0x68, 0xbd, 0x5c, 0x0e, 0xf7, 0x17, 0x69, 0xc6, 0xa5, 0xe3, 0x1b,
	0xa9, 0x5d, 0x74, 0x89, 0xa2, 0xfe, 0x6f, 0x1e, 0x9c, 0x14, 0x48, 0x0e, 0x01, 0xec, 0x6d, 0x16,
	0x91, 0xde, 0xb6, 0x48, 0xdb, 0xf4, 0xc4, 0x18, 0x93, 0x50, 0xeb, 0xa5, 0x2e, 0x7b, 0xc9, 0xde,
	0xa0, 0x97, 0x9a, 0x47, 0x5b, 0x1a, 0xd0, 0xf1, 0xd5, 0x65, 0x3f, 0x12, 0xc8, 0x94, 0x55, 0x97,
	0xe2, 0xb2, 0x8f, 0xa1, 0x81, 0x9d, 0x56, 0x52, 0x31, 0x35, 0x93, 0xb6, 0x25, 0xac, 0x34, 0x6f,
	0xa6, 0x2b, 0x26, 0xaf, 0x6a, 0x1b, 0x8b, 0x4e, 0x3b, 0x67, 0xf2, 0x2a, 0xdb, 0x86, 0x9b, 0x77,
	0xb5, 0xe1, 0x56, 0xb6, 0x0d, 0xdd, 0xdf, 0xf3, 0x50, 0x69, 0xce, 0x14, 0x9f, 0xb2, 0xfb, 0x0c,
	0xe7, 0xaf, 0x6d, 0x02, 0x0b, 0x26, 0x81, 0x9f, 0xa5, 0xc3, 0x9d, 0x25, 0x4b, 0xc4, 0x45, 0x42,
	0xdd, 0x27, 0xe0, 0xa4, 0x40, 0xb2, 0x09, 0xc5, 0x1f, 0x5a, 0xfd, 0x6a, 0x8e, 0x6c, 0x40, 0xa1,
	0xdb, 0xab, 0xe6, 0xdd, 0xef, 0x61, 0x67, 0xce, 0xb1, 0xd6, 0x77, 0x88, 0xeb, 0x59, 0xe9, 0x33,
	0x85, 0xed, 0x68, 0xcc, 0xef, 0x71, 0xd9, 0x5d, 0x28, 0x63, 0xc8, 0x82, 0x89, 0xe5, 0x8b, 0x05,
	0xbd, 0x71, 0x7a, 0xc5, 0x23, 0xf4, 0xa2, 0x59, 0x78, 0x81, 0xc2, 0x76, 0x92, 0x63, 0xb0, 0xae,
	0x81, 0xdc, 0x1f, 0x81, 0xa4, 0x0f, 0x5c, 0xe7, 0x65, 0x9e, 0x0e, 0x00, 0x16, 0xd6, 0x3a, 0x76,
	0xbd, 0xe7, 0xd5, 0x1c, 0x21, 0x50, 0x69, 0x77, 0x07, 0x2d, 0xda, 0x6d, 0x76, 0xbc, 0x16, 0xa5,
	0x3d, 0x5a, 0xcd, 0x93, 0x8f, 0x61, 0x8f, 0xb6, 0x5e, 0x0e, 0x5b, 0xfd, 0x81, 0xf7, 0x5d, 0x93,
	0x36, 0x5f, 0x78, 0xed, 0x4e, 0xa7, 0x75, 0xd6, 0xec, 0x54, 0x0b, 0x64, 0x07, 0x9c, 0xde, 0xe0,
	0xbc, 0x45, 0xad, 0xed, 0xe8, 0xf4, 0x8f, 0x12, 0x38, 0x43, 0x89, 0xa2, 0x8f, 0xe2, 0x4d, 0x30,
	0x42, 0x72, 0x06, 0x5b, 0xc9, 0xa7, 0x80, 0x1c, 0x64, 0x3d, 0xcd, 0x7c, 0x30, 0xea, 0x8f, 0x57,
	0x2b, 0xe3, 0x2b, 0xbb, 0x39, 0xf2, 0x33, 0xec, 0x9e, 0xa1, 0xd2, 0xd4, 0x99, 0x97, 0x88, 0x1c,
	0xdd, 0xf1, 0x48, 0xc5, 0xcc, 0xc7, 0xef, 0x7d, 0xc6, 0xdc, 0x1c, 0x79, 0x0d, 0x7b, 0x96, 0x3e,
	0x3b, 0x5c, 0xc9, 0xf1, 0x5d, 0x83, 0x37, 0x3e, 0xc0, 0x7d, 0xff, 0x6c, 0x76, 0x73, 0xe4, 0x25,
	0x54, 0xed, 0x09, 0xf3, 0x79, 0x42, 0x1e, 0xdf, 0x32, 0x66, 0x62, 0xde, 0xc3, 0x3b, 0x87, 0x90,
	0x9b, 0x23, 0xcf, 0xa1, 0xd2, 0x8f, 0x29, 0x6d, 0xbd, 0x93, 0xfa, 0xed, 0x8d, 0x54, 0x3f, 0x58,
	0xa9, 0x9b, 0x93, 0xbd, 0xd2, 0xff, 0x0c, 0x5d, 0x6b, 0x9a, 0x4f, 0xd7, 0x9b, 0x08, 0x99, 0x0a,
	0x78, 0x44, 0x0e, 0xb3, 0xf1, 0xbb, 0x51, 0xff, 0xf5, 0x27, 0xb7, 0xa9, 0x13, 0xe6, 0x8b, 0x0d,
	0xf3, 0xc3, 0xfc, 0xea, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0x09, 0x77, 0x1c, 0x6f, 0x0a,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetUserUploadHistory(ctx context.Context, in *UploadHistoryRequest, opts ...grpc.CallOption) (*UploadHistoryResponse, error)
	GetUserDepositHistory(ctx context.Context, in *DepositHistoryRequest, opts ...grpc.CallOption) (*DepositHistoryResponse, error)
	GetUserOrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error)
	SetUserAutopay(ctx context.Context, in *AutopayRequest, opts ...grpc.CallOption) (*AutopayResponse, error)
	UpdateUserInformation(ctx context.Context, in *UpdateInfoRequest, opts ...grpc.CallOption) (*UpdateInfoResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/soter_user.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserUploadHistory(ctx context.Context, in *UploadHistoryRequest, opts ...grpc.CallOption) (*UploadHistoryResponse, error) {
	out := new(UploadHistoryResponse)
	err := c.cc.Invoke(ctx, "/soter_user.UserService/GetUserUploadHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserDepositHistory(ctx context.Context, in *DepositHistoryRequest, opts ...grpc.CallOption) (*DepositHistoryResponse, error) {
	out := new(DepositHistoryResponse)
	err := c.cc.Invoke(ctx, "/soter_user.UserService/GetUserDepositHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserOrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error) {
	out := new(OrderListResponse)
	err := c.cc.Invoke(ctx, "/soter_user.UserService/GetUserOrderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetUserAutopay(ctx context.Context, in *AutopayRequest, opts ...grpc.CallOption) (*AutopayResponse, error) {
	out := new(AutopayResponse)
	err := c.cc.Invoke(ctx, "/soter_user.UserService/SetUserAutopay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUserInformation(ctx context.Context, in *UpdateInfoRequest, opts ...grpc.CallOption) (*UpdateInfoResponse, error) {
	out := new(UpdateInfoResponse)
	err := c.cc.Invoke(ctx, "/soter_user.UserService/UpdateUserInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetUserUploadHistory(context.Context, *UploadHistoryRequest) (*UploadHistoryResponse, error)
	GetUserDepositHistory(context.Context, *DepositHistoryRequest) (*DepositHistoryResponse, error)
	GetUserOrderList(context.Context, *OrderListRequest) (*OrderListResponse, error)
	SetUserAutopay(context.Context, *AutopayRequest) (*AutopayResponse, error)
	UpdateUserInformation(context.Context, *UpdateInfoRequest) (*UpdateInfoResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServiceServer) GetUserUploadHistory(ctx context.Context, req *UploadHistoryRequest) (*UploadHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserUploadHistory not implemented")
}
func (*UnimplementedUserServiceServer) GetUserDepositHistory(ctx context.Context, req *DepositHistoryRequest) (*DepositHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserDepositHistory not implemented")
}
func (*UnimplementedUserServiceServer) GetUserOrderList(ctx context.Context, req *OrderListRequest) (*OrderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOrderList not implemented")
}
func (*UnimplementedUserServiceServer) SetUserAutopay(ctx context.Context, req *AutopayRequest) (*AutopayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserAutopay not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUserInformation(ctx context.Context, req *UpdateInfoRequest) (*UpdateInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserInformation not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soter_user.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserUploadHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserUploadHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soter_user.UserService/GetUserUploadHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserUploadHistory(ctx, req.(*UploadHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserDepositHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserDepositHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soter_user.UserService/GetUserDepositHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserDepositHistory(ctx, req.(*DepositHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soter_user.UserService/GetUserOrderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserOrderList(ctx, req.(*OrderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetUserAutopay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutopayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetUserAutopay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soter_user.UserService/SetUserAutopay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetUserAutopay(ctx, req.(*AutopayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUserInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUserInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soter_user.UserService/UpdateUserInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUserInformation(ctx, req.(*UpdateInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "soter_user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "GetUserUploadHistory",
			Handler:    _UserService_GetUserUploadHistory_Handler,
		},
		{
			MethodName: "GetUserDepositHistory",
			Handler:    _UserService_GetUserDepositHistory_Handler,
		},
		{
			MethodName: "GetUserOrderList",
			Handler:    _UserService_GetUserOrderList_Handler,
		},
		{
			MethodName: "SetUserAutopay",
			Handler:    _UserService_SetUserAutopay_Handler,
		},
		{
			MethodName: "UpdateUserInformation",
			Handler:    _UserService_UpdateUserInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
